name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cloud_firestore: 3.4.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.5.1
  firebase_core: 1.20.0
  firebase_storage: 10.3.3
  get: 4.6.5
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 8.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

